// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/sign/sign.proto

package sign

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Type int32

const (
	Type_START  Type = 0
	Type_STOP   Type = 1
	Type_STATUS Type = 2
)

var Type_name = map[int32]string{
	0: "START",
	1: "STOP",
	2: "STATUS",
}

var Type_value = map[string]int32{
	"START":  0,
	"STOP":   1,
	"STATUS": 2,
}

func (x Type) String() string {
	return proto.EnumName(Type_name, int32(x))
}

func (Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_afdd2bb21074f4ee, []int{0}
}

type Request struct {
	Type                 Type     `protobuf:"varint,1,opt,name=Type,proto3,enum=sign.Type" json:"Type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_afdd2bb21074f4ee, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_START
}

type Response struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_afdd2bb21074f4ee, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterEnum("sign.Type", Type_name, Type_value)
	proto.RegisterType((*Request)(nil), "sign.Request")
	proto.RegisterType((*Response)(nil), "sign.Response")
}

func init() { proto.RegisterFile("proto/sign/sign.proto", fileDescriptor_afdd2bb21074f4ee) }

var fileDescriptor_afdd2bb21074f4ee = []byte{
	// 146 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0xce, 0x4c, 0xcf, 0x03, 0x13, 0x7a, 0x60, 0xbe, 0x10, 0x0b, 0x88, 0xad, 0xa4,
	0xc9, 0xc5, 0x1e, 0x94, 0x5a, 0x58, 0x9a, 0x5a, 0x5c, 0x22, 0x24, 0xc7, 0xc5, 0x12, 0x52, 0x59,
	0x90, 0x2a, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x67, 0xc4, 0xa5, 0x07, 0x56, 0x0b, 0x12, 0x09, 0x02,
	0x8b, 0x2b, 0xc9, 0x70, 0x71, 0x04, 0xa5, 0x16, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0x09, 0x70,
	0x31, 0xfb, 0x16, 0xa7, 0x83, 0x95, 0x72, 0x06, 0x81, 0x98, 0x5a, 0xea, 0x10, 0xdd, 0x42, 0x9c,
	0x5c, 0xac, 0xc1, 0x21, 0x8e, 0x41, 0x21, 0x02, 0x0c, 0x42, 0x1c, 0x5c, 0x2c, 0xc1, 0x21, 0xfe,
	0x01, 0x02, 0x8c, 0x42, 0x5c, 0x5c, 0x6c, 0xc1, 0x21, 0x8e, 0x21, 0xa1, 0xc1, 0x02, 0x4c, 0x49,
	0x6c, 0x60, 0xeb, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x90, 0xb8, 0x80, 0x04, 0x97, 0x00,
	0x00, 0x00,
}
