// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/model/model.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserMode int32

const (
	UserMode_OPEN         UserMode = 0
	UserMode_KEY          UserMode = 1
	UserMode_REGIST_OPEN  UserMode = 2
	UserMode_REGIST_CODE  UserMode = 3
	UserMode_REGIST_ADMIN UserMode = 4
)

var UserMode_name = map[int32]string{
	0: "OPEN",
	1: "KEY",
	2: "REGIST_OPEN",
	3: "REGIST_CODE",
	4: "REGIST_ADMIN",
}

var UserMode_value = map[string]int32{
	"OPEN":         0,
	"KEY":          1,
	"REGIST_OPEN":  2,
	"REGIST_CODE":  3,
	"REGIST_ADMIN": 4,
}

func (x UserMode) String() string {
	return proto.EnumName(UserMode_name, int32(x))
}

func (UserMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5d95f8c3a6adfa7f, []int{0}
}

type Type int32

const (
	// ghost-master service
	Type_START  Type = 0
	Type_STOP   Type = 1
	Type_STATUS Type = 2
)

var Type_name = map[int32]string{
	0: "START",
	1: "STOP",
	2: "STATUS",
}

var Type_value = map[string]int32{
	"START":  0,
	"STOP":   1,
	"STATUS": 2,
}

func (x Type) String() string {
	return proto.EnumName(Type_name, int32(x))
}

func (Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5d95f8c3a6adfa7f, []int{1}
}

type Status int32

const (
	Status_Success  Status = 0
	Status_AuthFail Status = 1
)

var Status_name = map[int32]string{
	0: "Success",
	1: "AuthFail",
}

var Status_value = map[string]int32{
	"Success":  0,
	"AuthFail": 1,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5d95f8c3a6adfa7f, []int{2}
}

// use this to check model version, so it can't be changed!
type Version struct {
	CurrentVersion       string   `protobuf:"bytes,1,opt,name=CurrentVersion,proto3" json:"CurrentVersion,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Version) Reset()         { *m = Version{} }
func (m *Version) String() string { return proto.CompactTextString(m) }
func (*Version) ProtoMessage()    {}
func (*Version) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d95f8c3a6adfa7f, []int{0}
}

func (m *Version) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Version.Unmarshal(m, b)
}
func (m *Version) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Version.Marshal(b, m, deterministic)
}
func (m *Version) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Version.Merge(m, src)
}
func (m *Version) XXX_Size() int {
	return xxx_messageInfo_Version.Size(m)
}
func (m *Version) XXX_DiscardUnknown() {
	xxx_messageInfo_Version.DiscardUnknown(m)
}

var xxx_messageInfo_Version proto.InternalMessageInfo

func (m *Version) GetCurrentVersion() string {
	if m != nil {
		return m.CurrentVersion
	}
	return ""
}

// 用户信息
type User struct {
	User                 string   `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	Pass                 []byte   `protobuf:"bytes,2,opt,name=Pass,proto3" json:"Pass,omitempty"`
	Domain               []string `protobuf:"bytes,3,rep,name=Domain,proto3" json:"Domain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d95f8c3a6adfa7f, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *User) GetPass() []byte {
	if m != nil {
		return m.Pass
	}
	return nil
}

func (m *User) GetDomain() []string {
	if m != nil {
		return m.Domain
	}
	return nil
}

// 域
type Domain struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Jump                 string   `protobuf:"bytes,2,opt,name=Jump,proto3" json:"Jump,omitempty"`
	IP                   string   `protobuf:"bytes,3,opt,name=IP,proto3" json:"IP,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Domain) Reset()         { *m = Domain{} }
func (m *Domain) String() string { return proto.CompactTextString(m) }
func (*Domain) ProtoMessage()    {}
func (*Domain) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d95f8c3a6adfa7f, []int{2}
}

func (m *Domain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Domain.Unmarshal(m, b)
}
func (m *Domain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Domain.Marshal(b, m, deterministic)
}
func (m *Domain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Domain.Merge(m, src)
}
func (m *Domain) XXX_Size() int {
	return xxx_messageInfo_Domain.Size(m)
}
func (m *Domain) XXX_DiscardUnknown() {
	xxx_messageInfo_Domain.DiscardUnknown(m)
}

var xxx_messageInfo_Domain proto.InternalMessageInfo

func (m *Domain) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Domain) GetJump() string {
	if m != nil {
		return m.Jump
	}
	return ""
}

func (m *Domain) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

// 服务器配置
type ServerConfig struct {
	UserMode             UserMode `protobuf:"varint,1,opt,name=UserMode,proto3,enum=model.UserMode" json:"UserMode,omitempty"`
	MaxUser              int64    `protobuf:"varint,2,opt,name=MaxUser,proto3" json:"MaxUser,omitempty"`
	MaxDomain            int64    `protobuf:"varint,3,opt,name=MaxDomain,proto3" json:"MaxDomain,omitempty"`
	MaxDomainPerUser     int64    `protobuf:"varint,4,opt,name=MaxDomainPerUser,proto3" json:"MaxDomainPerUser,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerConfig) Reset()         { *m = ServerConfig{} }
func (m *ServerConfig) String() string { return proto.CompactTextString(m) }
func (*ServerConfig) ProtoMessage()    {}
func (*ServerConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d95f8c3a6adfa7f, []int{3}
}

func (m *ServerConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerConfig.Unmarshal(m, b)
}
func (m *ServerConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerConfig.Marshal(b, m, deterministic)
}
func (m *ServerConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerConfig.Merge(m, src)
}
func (m *ServerConfig) XXX_Size() int {
	return xxx_messageInfo_ServerConfig.Size(m)
}
func (m *ServerConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ServerConfig proto.InternalMessageInfo

func (m *ServerConfig) GetUserMode() UserMode {
	if m != nil {
		return m.UserMode
	}
	return UserMode_OPEN
}

func (m *ServerConfig) GetMaxUser() int64 {
	if m != nil {
		return m.MaxUser
	}
	return 0
}

func (m *ServerConfig) GetMaxDomain() int64 {
	if m != nil {
		return m.MaxDomain
	}
	return 0
}

func (m *ServerConfig) GetMaxDomainPerUser() int64 {
	if m != nil {
		return m.MaxDomainPerUser
	}
	return 0
}

// 邀请码(JWT载荷)
type InviteCode struct {
	MaxDomain            int64    `protobuf:"varint,1,opt,name=MaxDomain,proto3" json:"MaxDomain,omitempty"`
	DefaultDomain        string   `protobuf:"bytes,2,opt,name=DefaultDomain,proto3" json:"DefaultDomain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InviteCode) Reset()         { *m = InviteCode{} }
func (m *InviteCode) String() string { return proto.CompactTextString(m) }
func (*InviteCode) ProtoMessage()    {}
func (*InviteCode) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d95f8c3a6adfa7f, []int{4}
}

func (m *InviteCode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InviteCode.Unmarshal(m, b)
}
func (m *InviteCode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InviteCode.Marshal(b, m, deterministic)
}
func (m *InviteCode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InviteCode.Merge(m, src)
}
func (m *InviteCode) XXX_Size() int {
	return xxx_messageInfo_InviteCode.Size(m)
}
func (m *InviteCode) XXX_DiscardUnknown() {
	xxx_messageInfo_InviteCode.DiscardUnknown(m)
}

var xxx_messageInfo_InviteCode proto.InternalMessageInfo

func (m *InviteCode) GetMaxDomain() int64 {
	if m != nil {
		return m.MaxDomain
	}
	return 0
}

func (m *InviteCode) GetDefaultDomain() string {
	if m != nil {
		return m.DefaultDomain
	}
	return ""
}

type Request struct {
	Type                 Type     `protobuf:"varint,1,opt,name=Type,proto3,enum=model.Type" json:"Type,omitempty"`
	Auth                 *User    `protobuf:"bytes,2,opt,name=auth,proto3" json:"auth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d95f8c3a6adfa7f, []int{5}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_START
}

func (m *Request) GetAuth() *User {
	if m != nil {
		return m.Auth
	}
	return nil
}

type Response struct {
	Code                 Status   `protobuf:"varint,1,opt,name=Code,proto3,enum=model.Status" json:"Code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d95f8c3a6adfa7f, []int{6}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCode() Status {
	if m != nil {
		return m.Code
	}
	return Status_Success
}

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterEnum("model.UserMode", UserMode_name, UserMode_value)
	proto.RegisterEnum("model.Type", Type_name, Type_value)
	proto.RegisterEnum("model.Status", Status_name, Status_value)
	proto.RegisterType((*Version)(nil), "model.Version")
	proto.RegisterType((*User)(nil), "model.User")
	proto.RegisterType((*Domain)(nil), "model.Domain")
	proto.RegisterType((*ServerConfig)(nil), "model.ServerConfig")
	proto.RegisterType((*InviteCode)(nil), "model.InviteCode")
	proto.RegisterType((*Request)(nil), "model.Request")
	proto.RegisterType((*Response)(nil), "model.Response")
}

func init() { proto.RegisterFile("proto/model/model.proto", fileDescriptor_5d95f8c3a6adfa7f) }

var fileDescriptor_5d95f8c3a6adfa7f = []byte{
	// 458 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x92, 0xdd, 0x6e, 0xd3, 0x40,
	0x10, 0x85, 0xe3, 0x9f, 0xc6, 0xf1, 0x24, 0x4d, 0x57, 0x73, 0x01, 0xbe, 0x40, 0x22, 0x18, 0x04,
	0x51, 0x90, 0x8a, 0x80, 0x07, 0x80, 0xc8, 0x49, 0x91, 0xa9, 0x9c, 0x98, 0xb5, 0x8b, 0xc4, 0x15,
	0x5a, 0xda, 0x6d, 0x6b, 0x29, 0xb1, 0x83, 0x77, 0x5d, 0x95, 0xa7, 0xe1, 0x55, 0xd1, 0xae, 0x7f,
	0x42, 0xd3, 0x1b, 0x7b, 0xe6, 0x9b, 0xe3, 0xb3, 0x73, 0x56, 0x86, 0xa7, 0xbb, 0xb2, 0x90, 0xc5,
	0xbb, 0x6d, 0x71, 0xc5, 0x37, 0xf5, 0xf3, 0x54, 0x13, 0x3c, 0xd2, 0x8d, 0xff, 0x1e, 0x9c, 0xef,
	0xbc, 0x14, 0x59, 0x91, 0xe3, 0x6b, 0x18, 0x07, 0x55, 0x59, 0xf2, 0x5c, 0x36, 0xc4, 0x33, 0x26,
	0xc6, 0xd4, 0xa5, 0x07, 0xd4, 0x3f, 0x03, 0xfb, 0x42, 0xf0, 0x12, 0xb1, 0x7e, 0x37, 0xaa, 0x8e,
	0xc5, 0x4c, 0x08, 0xcf, 0x9c, 0x18, 0xd3, 0x11, 0xd5, 0x35, 0x3e, 0x81, 0xfe, 0xa2, 0xd8, 0xb2,
	0x2c, 0xf7, 0xac, 0x89, 0x35, 0x75, 0x69, 0xd3, 0xf9, 0x9f, 0x5b, 0xae, 0xbe, 0x5a, 0xb1, 0x2d,
	0x6f, 0x9d, 0x54, 0xad, 0xd8, 0xd7, 0x6a, 0xbb, 0xd3, 0x4e, 0x2e, 0xd5, 0x35, 0x8e, 0xc1, 0x0c,
	0x63, 0xcf, 0xd2, 0xc4, 0x0c, 0x63, 0xff, 0xaf, 0x01, 0xa3, 0x84, 0x97, 0x77, 0xbc, 0x0c, 0x8a,
	0xfc, 0x3a, 0xbb, 0xc1, 0xb7, 0x30, 0x50, 0x6b, 0x44, 0xc5, 0x55, 0x6d, 0x36, 0xfe, 0x70, 0x72,
	0x5a, 0x87, 0x6e, 0x31, 0xed, 0x04, 0xe8, 0x81, 0x13, 0xb1, 0x7b, 0x1d, 0x41, 0x1d, 0x62, 0xd1,
	0xb6, 0xc5, 0x67, 0xe0, 0x46, 0xec, 0xbe, 0x5b, 0x5a, 0xcd, 0xf6, 0x00, 0x67, 0x40, 0xba, 0x26,
	0xe6, 0xa5, 0x36, 0xb0, 0xb5, 0xe8, 0x11, 0xf7, 0x63, 0x80, 0x30, 0xbf, 0xcb, 0x24, 0x0f, 0xd4,
	0x89, 0x0f, 0x7c, 0x8d, 0x43, 0xdf, 0x57, 0x70, 0xbc, 0xe0, 0xd7, 0xac, 0xda, 0xc8, 0x46, 0x51,
	0x47, 0x7f, 0x08, 0xfd, 0x73, 0x70, 0x28, 0xff, 0x5d, 0x71, 0x21, 0xf1, 0x39, 0xd8, 0xe9, 0x9f,
	0x5d, 0x9b, 0x74, 0xd8, 0x24, 0x55, 0x88, 0xea, 0x81, 0x12, 0xb0, 0x4a, 0xde, 0x6a, 0xa3, 0x61,
	0x27, 0x50, 0x8b, 0x51, 0x3d, 0xf0, 0x3f, 0xc1, 0x80, 0x72, 0xb1, 0x2b, 0x72, 0xc1, 0xf1, 0x05,
	0xd8, 0xc1, 0xfe, 0xde, 0x8e, 0x1b, 0x71, 0x22, 0x99, 0xac, 0x04, 0xd5, 0x23, 0x24, 0x60, 0x45,
	0xe2, 0xa6, 0xd9, 0x4b, 0x95, 0xb3, 0x6f, 0xfb, 0x0b, 0xc7, 0x01, 0xd8, 0xeb, 0x78, 0xb9, 0x22,
	0x3d, 0x74, 0xc0, 0x3a, 0x5f, 0xfe, 0x20, 0x06, 0x9e, 0xc0, 0x90, 0x2e, 0xbf, 0x84, 0x49, 0xfa,
	0x53, 0x4f, 0xcc, 0xff, 0x40, 0xb0, 0x5e, 0x2c, 0x89, 0x85, 0x04, 0x46, 0x0d, 0x98, 0x2f, 0xa2,
	0x70, 0x45, 0xec, 0xd9, 0x9b, 0x3a, 0x15, 0xba, 0x70, 0x94, 0xa4, 0x73, 0x9a, 0x92, 0x9e, 0x72,
	0x4e, 0xd2, 0x75, 0x4c, 0x0c, 0x04, 0xe8, 0x27, 0xe9, 0x3c, 0xbd, 0x48, 0x88, 0x39, 0x7b, 0x09,
	0xfd, 0x7a, 0x3b, 0x1c, 0x82, 0x93, 0x54, 0x97, 0x97, 0x5c, 0x08, 0xd2, 0xc3, 0x11, 0x0c, 0xe6,
	0x95, 0xbc, 0x3d, 0x63, 0xd9, 0x86, 0x18, 0xbf, 0xfa, 0xfa, 0x6f, 0xff, 0xf8, 0x2f, 0x00, 0x00,
	0xff, 0xff, 0x1a, 0x27, 0xc9, 0x95, 0x08, 0x03, 0x00, 0x00,
}
